Updated to support templating with cached creds, puppet 4 futureparse fixes and adjusted purge_sssd to happen only if the network can contact the domain specified via ping

diff --git a/templates/purge_sssd.erb b/templates/purge_sssd.erb
--- a/templates/purge_sssd.erb
+++ b/templates/purge_sssd.erb
@@ -1,4 +1,30 @@
 #!/bin/bash
 
-printf " - Purging SSSD cache\n"
-rm -rf /var/lib/sss/{db,mc}/*
+function networkup {
+  # Initialize number of attempts
+  reachable=$1
+  while [ $reachable -ne 0 ]; do
+    # Ping supplied host
+    ping -q -c 1 -W 1 "$2" > /dev/null 2>&1
+    # Check return code
+    if [ $? -eq 0 ]; then
+      # Success, we can exit with the right return code
+      echo 0
+      return
+    fi
+    # Network down, decrement counter and try again
+    let reachable-=1
+    # Sleep for one second
+    sleep 1
+  done
+  # Network down, number of attempts exhausted, quiting
+  echo 1
+}
+
+printf " - purge_sssd is checking if AD is reachable before purging\n"
+if [ $(networkup 30 <%= @domain %>) -eq 0 ]; then
+  printf " - Purging SSSD cache\n"
+  rm -rf /var/lib/sss/{db,mc}/*
+else
+  printf " - Unable to Purge SSSD cache, ad.sfu.ca was not reachable\n"
+fi
